name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: preconfig
      run: apt update -y && apt install -y graphviz
    - name: configure
      run: ./configure
    - name: make
      run: make
